version: "3.3"

services:
  marsy-payload-service:
    image: "nestjs-marsy/marsy-payload"
    restart: always
    ports:
      - 3006:3000

    networks:
      - nestjs-marsy-network

networks:
  nestjs-marsy-network:
    driver: bridge