version: "1"

services:
  gateway:
    image: "nestjs-marsy/gateway"
    restart: always
    ports:
      - 9500:3000
    depends_on:
      - ${MARSY_ROCKET_SERVICE}
      - ${MARSY_WEATHER_SERVICE}
    environment:
      - MARSY_ROCKET_SERVICE_URL_WITH_PORT=${MARSY_ROCKET_SERVICE}:3000
      - MARSY_WEATHER_SERVICE_URL_WITH_PORT=${MARSY_WEATHER_SERVICE}:3000
    networks:
        - nestjs-marsy-network
networks:
  nestjs-marsy-network:
    driver: bridge