version: "3.3"

services:
  zookeeper:
    container_name: soa-team-d-zookeeper
    restart: unless-stopped
    image: wurstmeister/zookeeper
    environment:
      zk_id: "1"
    expose:
      - 2181
    networks:
      - nestjs-marsy-network

  kafka-service:
    container_name: soa-team-e-kafka
    restart: unless-stopped
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-service
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: soa-team-d-zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "topic-mission-events:3:1,telemetry:1:1,events-web-caster:1:1,booster-telemetry:1:1,controlpad-telemetry:1:1,mission-telemetry1:1,payload-telemetry:1:1,client-service-events:1:1,broadcast-service:1:1"
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    expose:
      - 9092
    networks:
      - nestjs-marsy-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "soa-team-d-zookeeper:2181"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nestjs-marsy-network:
    driver: bridge
