version: "3.3"

services:
  marsy-webcaster-service:
    image: "nestjs-marsy/marsy-webcaster"
    restart: always
    ports:
      - 3011:3000
    networks:
      - nestjs-marsy-network
    external_links:
      - docker-compose-kafka-service:kafka-service:kafka-service
networks:
  nestjs-marsy-network:
    driver: bridge