@startuml
skinparam componentStyle rectangle
left to right direction


rectangle "Marsy Microservices" as backend {


    component "Missions Service" as s_mission     
    
    component "controlpad Service" as s_rocket
    component "Weather Service" as s_weather

    component "Telemetry Service" as s_telemtry

    component "Booster service" as s_booster
    component "Payload service" as s_payload

    database "Rockets DB" as db_rockets
    database "Missions DB" as db_missions
    database "Telemetry DB" as db_telemetry
    s_telemtry --> s_rocket: telemetries
    s_telemtry --> s_booster : telemetries
    s_telemtry --> s_mission : telemetries


    s_payload -->  s_rocket : notify  reaching orbit
    s_payload <-- s_telemtry  : telemetries

    s_booster --> s_mission :Booster Recovery
    s_rocket --> s_mission : send commands
    s_rocket <--s_mission : launch/destroy rocket
    s_weather <--s_mission

    s_mission --> db_missions
    s_rocket --> db_rockets
    s_telemtry --> db_telemetry
}

component "Mock Service" as s_mock
 s_mock --> s_telemtry : telemetries


@enduml